name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, x64, GPU]
    container:
      image: nvidia/cuda:12.5.0-devel-ubuntu22.04
      options: --gpus all

    steps:
    - uses: actions/checkout@v4
    - run: nvidia-smi
    - run: nvcc -V
    - run: make
    - run: make test
